### PR TITLE
fix(errors): Do not check for Google Cloud SDK if using an s3 bucket_url

### PR DESCRIPTION
**Pull request by richardARPANET**
Before:

```
>> shaka-streamer -i input.yml -p pipeline.yml -c s3://local-media/out/

Fatal error:
  Google Cloud SDK not found! Please install version 212.0.0 or higher of Google Cloud SDK.
```

After:

No error, it runs.

### CODE REVIEW

**Comment by joeyparrish** [comment]
If tests are not running, could it be because your PR is in draft mode?  I think first-time contributors might need approval to run tests in GitHub Actions, but I don't see a button for that, presumably because it's just a draft PR.

Feel free to convert it to "ready", even if it's not completely.  :-)

**Comment by richardARPANET** [comment]
@joeyparrish I just re-enabled the `build_and_test.yaml` Github action. Maybe it'll now show you something to approve?

**Comment by richardARPANET** [comment]
It's working now I think. Not yet "ready" really, will comment again when it is.

**Comment by joeyparrish** [comment]
Sound good.  I saw the approval button, and I clicked it.

**Comment by richardARPANET** [comment]
@joeyparrish could you approve that Github action again? For some reason it's asking for approve upon every new commit..

**Comment by joeyparrish** [comment]
Workflow triggered.

I'm a little confused about your change, though.  The cloud upload node is still using gsutil to upload to s3:// URLs, right?  So why would you not want to check for the Google Cloud SDK?

**Comment by richardARPANET** [comment]
Ah, I didn't know that was even a feature of gsutil :) Will close this then.

**Comment by joeyparrish** [comment]
No worries.  I see you had done a lot of the work needed to re-enable the test workflow.  Would you be willing to put up a PR that focuses on that?

**Pull request closed without merging**
